# Generated by Django 5.2.5 on 2025-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_permission_role_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="departments", to="users.role"
            ),
        ),
    ]
