# Generated by Django 5.2.5 on 2025-08-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_first_name_user_last_name_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.permission"
            ),
        ),
    ]
