name: CI/CD Docker Deploy

on:
  push:
    branches:
      - main  # Make sure your default branch is named "main"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # Build Django Docker image
      - name: Build Django image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/strategybackend-web:latest -f Dockerfile .

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      # Install SSH client
      - name: Install SSH
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      # Set up SSH agent with private key
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Deploy to EC2
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            # Clone repo if it does not exist
            if [ ! -d ~/strategybackend ]; then
              git clone git@github.com:Gudisa1/Strategy-Backend.git ~/strategybackend
            fi

            cd ~/strategybackend
            git pull origin main

            # Create .env file
            cat > .env <<EOF
SECRET_KEY='"${{ secrets.SECRET_KEY }}"'
DEBUG='"${{ secrets.DEBUG }}"'
POSTGRES_DB='"${{ secrets.POSTGRES_DB }}"'
POSTGRES_USER='"${{ secrets.POSTGRES_USER }}"'
POSTGRES_PASSWORD='"${{ secrets.POSTGRES_PASSWORD }}"'
DB_HOST='"${{ secrets.DB_HOST }}"'
DB_PORT='"${{ secrets.DB_PORT }}"'
ALLOWED_HOSTS='"${{ secrets.ALLOWED_HOSTS }}"'
EOF

            # Pull and run Docker Compose
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --build
          '
